# Setup Monitors
# cable is broken, need to fix someday to recognice resolution
# monitor = desc:Fujitsu Siemens Computers GmbH B22W-6 LED YV3U123716,    1680x1050@59.95,    0x0,    1, transform, 0
monitor = desc:Fujitsu Siemens Computers GmbH B22W-6 LED YV3U123716, disable
# monitor = DP-1,                                                         1680x1050@59.95,    0x0,    1, transform, 0

monitor = desc:AOC Q27G4N 2KQR1HA000189,                                2560x1440@180, 1920x0,  1, transform, 0
# monitor = desc:AOC Q27G4N 2KQR1HA000189, highrr, auto, 1
monitor = desc:LG Electronics 32inch LG FHD 0x01010101,                 1920x1080@60.0,     0x0,	1, transform, 0
monitor = desc:Fujitsu Siemens Computers GmbH B19-7 LED YV6V005490,     1280x1024@60.02, 4480x0,	1, transform, 1

# # Workspace rules layout
workspace = name:game,  monitor:desc:AOC Q27G4N 2KQR1HA000189
