# Restrict tablet only on integrated Screen
device {
  name = wacom-pen-and-multitouch-sensor-pen
  transform = 0
  output=eDP-1
}

# Restrict touch-sensor only on integrated Screen
device {
  name = wacom-pen-and-multitouch-sensor-finger
  transform = 0
  output=eDP-1
}

decoration {
  blur:enabled = false
  shadow:enabled = false
}

misc {
vfr = true
}
