require("luasnip.loaders.from_vscode").lazy_load()
require("luasnip").config.setup({})
require("luasnip").filetype_extend("lua", { "luadoc" })
require("luasnip").filetype_extend("rust", { "rustdoc" })
require("luasnip").filetype_extend("cs", { "csharpdoc" })
require("luasnip").filetype_extend("java", { "javadoc" })
require("luasnip").filetype_extend("c", { "cdoc" })
require("luasnip").filetype_extend("cpp", { "cppdoc" })
require("luasnip").filetype_extend("norg", { "markdown", "text" })
