hl.on("hyprland.start", function()
    -- Core stuff
    hl.exec_cmd("dunst")
    hl.exec_cmd("/usr/lib/polkit-gnome-polkit-gnome-authentication-agent-1")
    hl.exec_cmd("firewalld")
    hl.exec_cmd("start-xdg-desktop-portal")
    hl.exec_cmd("wl-paste --watch cliphist store")
    -- Audio
    hl.exec_cmd("initialize-sinks")
    hl.exec_cmd("easyeffects --hide-window")
    -- Workspace Interface
    hl.exec_cmd("awww-daemon & chwp -r")
    hl.exec_cmd("waybar")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("nextcloud")
    hl.exec_cmd("steam -silent")
    hl.exec_cmd("signal-desktop")
    hl.exec_cmd("karere")
    hl.exec_cmd("vesktop -m")
end)
hl.on("config.reloaded", function()
    -- Reload Workspace Interface
    hl.exec_cmd("chwp -r")
    hl.exec_cmd("pkill waybar; waybar")
    hl.exec_cmd("pkill blueman-applet; blueman-applet")
end)
