#!/bin/bash

# Default values
reload=false
loadingscreen=false
transition_type="any"
allowed_transition_types=("none" "simple" "fade" "left" "right" "top" "bottom" "wipe" "wave" "grow" "center" "any" "outer" "random")
loadingscreenPath=~/.config/hypr/loadingscreen
lockscreenpath=~/.config/hypr/lockscreen
wallpaperPath=~/.config/hypr/wallpaper
sddmPath=/usr/share/sddm/themes/sugar-candy/Backgrounds/wallpaper
cachepath=~/.cache/swww

# Functions
set_new_wallpaper() {
  cp "$filepath" "$wallpaperPath" && action="loaded: "
  
  if [ $(file -b --mime-type "$filepath") == "image/gif" ]; then
    convert "$filepath[0]" "$lockscreenpath"
    sudo rm ~/.cache/swww/*
  else
    cp "$filepath" "$lockscreenpath"
  fi
  cp "$lockscreenpath" "$sddmPath"
  load_loadingscreen 
  swww img "$wallpaperPath" --transition-type "$transition_type" && sleep 4
}

reload_wallpaper() {
  swww img "$wallpaperPath" --transition-type "$transition_type"
  sleep 4
  action="reloaded with '$transition_type' transition type"
}

load_loadingscreen() {
  swww img "$loadingscreenPath" --transition-type "$transition_type"
  sleep 4
}

# Display help message
display_help() {
  cat << EOF
Usage: chwp [-r <transition_type>] [-t <transition_type>] [-l] [<filename>]

Set a new wallpaper on the system using the swww command.

Options:
  -r <transition_type>  Set the transition type when reloading the wallpaper (default value: $transition_type)
                        Supported types are: ${allowed_transition_types[@]}
  -t <transition_type>  Set the transition type when applying a new wallpaper (default value: $transition_type)
                        Supported types are: ${allowed_transition_types[@]}
  -l                    Display the loading screen
  -h                    Display this help message

Arguments:
  <filename>            Path to the image file to set as the wallpaper

Default Values:
  Wallpaper Path: $wallpaperPath
  SDDM Wallpaper Path: $sddmPath

Examples:
  $0 -r wipe       # Reload with 'wipe' transition type
  $0 -t wipe image.jpg     # Set 'image.jpg' as the new wallpaper with 'wipe' transition
EOF
}

# Validate transition type
validate_transition_type() {
  local input_transition_type=$1
  if [[ ! " ${allowed_transition_types[@]} " =~ " $input_transition_type " ]]; then
    echo "Invalid transition type: $input_transition_type. Supported types are: ${allowed_transition_types[@]}" >&2
    exit 1
  fi
}

# Parse command line options
while getopts ":r:t:lh" opt; do
  case ${opt} in
    r)
      reload=true
      transition_type="${OPTARG:-$transition_type}"
      validate_transition_type "$transition_type"
      ;;
    t)
      transition_type="${OPTARG:-$transition_type}"
      validate_transition_type "$transition_type"
      ;;
    l)
      loadingscreen=true
      ;;
    h)
      display_help
      exit 0
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done
shift $((OPTIND - 1))

# Extract filename
filename="$1"

# Check if file exists
filepath=$(readlink -f "$filename")
if [ "$filename" ] && [ ! -f "$filepath" ]; then
  echo "File not found: $filename" >&2
  exit 1
fi

# Main execution
if [ "$loadingscreen" = true ]; then
  load_loadingscreen
elif [ "$reload" = true ]; then
  reload_wallpaper
elif [ "$filename" ]; then
  set_new_wallpaper
else
  display_help
fi

