#!/bin/bash

display_help() {
	cat <<EOF
Help:
--------------------------------------
regex : idle-mode <mode>
	
modes:
 on     : start idle-mode
 off    : stop  idle-mode
 switch : switches between on and off
 info   : outputs the current state
EOF
	exit 0
}

activate_idle_mode() {
	exec swayidle -w timeout $screensavertime 'hyprctl dispatch dpms off' \
		resume 'hyprctl dispatch dpms on' \
		timeout $locktime "$HOME/.config/hypr/scripts/lock" \
		resume 'hyprctl dispatch dpms on' \
		timeout $suspendtime 'hyprctl dispatch dpms on & pkill swaylock & systemctl suspend' \
		after-resume "$HOME/.config/hypr/scripts/lock -n" &
	notify-send "$(idle-mode info)"
	exit 1
}

deactivate_idle_mode() {
	pkill swayidle
	notify-send "$(idle-mode info)"
	exit 1
}

switch_modes() {
	if [ -n "$(pgrep swayidle)" ]; then
		deactivate_idle_mode
	else
		activate_idle_mode
	fi
}

info() {
	if [ -n "$(pgrep swayidle)" ]; then
		echo "idle-mode is currently on"
	else
		echo "idle-mode is currently off"
	fi
	exit 1
}

waybar() {
	while true; do
		if [ -n "$(pgrep swayidle)" ]; then
			echo "{\"text\": \"\", \"alt\": \"on\", \"tooltip\": \"Idle mode currently on\", \"class\": \"on\" }"
		else
			echo "{\"text\": \"\", \"alt\": \"off\", \"tooltip\": \"Idle mode currently off\", \"class\": \"off\" }"
		fi
		sleep 0.5
	done
	exit 1
}

# Default values
screensavertime=600
lockdelay=60
suspeddelay=600

locktime=$(($screensavertime + $lockdelay))
suspendtime=$(($locktime + $suspeddelay))

# Check if a mode is provided
if [ $# -eq 0 ]; then
	display_help
fi

if [[ $1 = "on" ]]; then
	activate_idle_mode
elif [[ $1 = "off" ]]; then
	deactivate_idle_mode
elif [[ $1 = "switch" ]]; then
	switch_modes
elif [[ $1 = "info" ]]; then
	info
elif [[ $1 = "waybar" ]]; then
	waybar
else
	display_help
fi
