#!/bin/bash

gnomeschema=org.gnome.desktop.interface

display_help() {
  echo "Usage: $0 [OPTION] VALUE"
  echo "Change GNOME desktop settings."
  echo
  echo "Options:"
  echo "  --gtk-theme    Change GTK theme"
  echo "  --icon-theme   Change icon theme"
  echo "  --cursor-theme Change cursor theme"
  echo "  --cursor-size  Change cursor size"
  echo "  --font-name    Change font name"
  echo
  echo "Example: $0 --gtk-theme Adwaita"
}

change_gtk_theme() {
  gsettings set $gnomeschema gtk-theme "$2" 
  exit 0
}

change_icon_theme() {
  gsettings set $gnomeschema icon-theme "$2" 
  exit 0
}

change_cursor_theme() {
  gsettings set $gnomeschema cursor-theme "$2" 
  exit 0
}

change_cursor_size() {
  gsettings set $gnomeschema cursor-size "$2" 
  exit 0
}

change_font_name() {
  gsettings set $gnomeschema font-name "$2" 
  exit 0
}

if [ "$#" -ne 2 ]; then
  display_help
  exit 1
fi

case "$1" in
  --gtk-theme)
    change_gtk_theme "$2"
    ;;
  --icon-theme)
    change_icon_theme "$2"
    ;;
  --cursor-theme)
    change_cursor_theme "$2"
    ;;
  --cursor-size)
    change_cursor_size "$2"
    ;;
  --font-name)
    change_font_name "$2"
    ;;
  *)
    echo "Invalid option"
    display_help
    ;;
esac
