#!/usr/bin/env bash

# Calculate updates for each service
A=$(yay -Sy)
UPDATES=$(yay -Qu | wc -l)


# If the parameter is "update", update all services
if [ "$1" = "update" ]; then
    kitty --title update-sys sh -c 'yay -Syu'
    pkill -RTMIN+8 waybar
fi

# If there aren't any parameters, return the total number of updates
if [ "$1" = "" ]; then
    # Calculate total number of updates
    if [[ "$UPDATES" = "0" ]]
    then
      echo ""
    else
        # This Update symbol is RTL. So &#x202d; is left-to-right override.
      echo " $UPDATES"
    fi
    exit 0
fi
