# This config contains The monitor Layout and thier workspace rules
# to see the options go to https://wiki.hyprland.org/Configuring/Monitors

monitor = desc:Chimei Innolux Corporation 0x1387, 1920x1080@60.0, 0x0, 1, transform, 0 # Laptop Screen
monitor = , preferred, auto, 1
