[main]
### APPEARANCE ###
font = JetBrains Mono Nerd Font:size=14
layer = overlay
anchor = center
lines = 10
line-height = 20
letter-spacing = 0
width = 40

### PADDING ###
horizontal-pad = 20
vertical-pad = 20
inner-pad = 5

### BEHAVIOR ###
terminal = foot
exit-on-keyboard-focus-loss = yes
show-actions = no
prompt = " Search: "
fields = name,generic,comment,categories,filename,keywords
dpi-aware = no

### ICONS ###
icons-enabled = yes
# icon-theme = MoreWaita
icon-theme = Papirus

[border]
width = 2
radius = 12

[colors]
background = 0F0F17ff
text = a9b1d6ff
selection = a1bdceff
selection-text = 0F0F17ff
border = a1bdceff
match = 7aa2f7ff
