# This config contains The monitor Layout and thier workspace rules
# to see the options go to https://wiki.hyprland.org/Configuring/Monitors

monitor = desc:AOC Q27G4N 2KQR1HA000189,                            2560x1440@180,    1920x0, 1, transform, 0 # Main monitor
monitor = desc:LG Electronics 32inch LG FHD 0x01010101,             1920x1080@60.0,   0x0,	  1, transform, 0 # Left monitor
monitor = desc:Fujitsu Siemens Computers GmbH B19-7 LED YV6V005490, 1280x1024@60.02,  4480x0,	1, transform, 1 # Right monitor
# Workspace rules layout
workspace = name:game,  monitor:desc:AOC Q27G4N 2KQR1HA000189                                 # Workspace rule for games
workspace = 3,  monitor:desc:LG Electronics 32inch LG FHD 0x01010101              # Workspace rule for default monitor 1 workspace
workspace = 2,  monitor:desc:AOC Q27G4N 2KQR1HA000189                             # Workspace rule for default monitor 2 workspace
workspace = 1,  monitor:desc:Fujitsu Siemens Computers GmbH B19-7 LED YV6V005490  # Workspace rule for default monitor 3 workspace

# move mouse to main monitor on startup
exec-once = hyprctl dispatch workspace name:2
