#-System-required-processes-#
### system-needed ###
exec-once = dunst	# notification-agent
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1	# auth-agent
exec-once = firewalld		# firewall
exec-once = hypridle		# idle-mode
exec-once = hyprpm reload	# hyprland plugins

## desktop-portal for streaming ##
exec-once = start-xdg-desktop-portal
# exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

## load wallpaper ##
exec = swww-daemon  # wallpaper-agent
exec = chwp -r  # sets-wallpaper

## audio ##
exec-once = initialize-sinks # setup sinks for pipewire
exec-once = easyeffects --gapplication-service # easyeffects

## docker ##
exec = pkill waybar; waybar	# dock

### applets ###
exec-once = bitwarden-desktop # bitwarden-apllet
exec = pkill blueman-applet; blueman-applet # bluetooth-applet
exec = pkill nm-applet; nm-applet # network-manager-applet

## Applications ##
exec-once = lact daemon		#GPU overclocking
exec-once = exec wl-paste --watch cliphist store #clipboard history
exec = pkill nextcloud; nextcloud				# nextcloud-client
exec = pkill steam; steam -silent
exec = pkill discord; discord --start-minimized
exec = pkill signal; signal
exec = pkill obs; obs --minimize-to-tray --disable-shutdown-check

# move mouse to main monitor on startup
exec-once = hyprctl dispatch workspace 2
