# This config controls the decoration of Hyprland

misc {
disable_hyprland_logo = yes						# disable hyprland-logo splashscreen on login
}

# Workspace decoration
general {
  gaps_in = 5								# gap-size between windows
  gaps_out = 11							# gap-size between screen-edges
  border_size = 2
  col.active_border = rgba(A1BDCEFF)		# active window-border
  col.inactive_border = rgba(27272EFF)				# inactive window-border
  layout = dwindle							# window layout
  snap {
	  enabled = true
	  window_gap = 10
	  monitor_gap = 10
	  border_overlap = false
	}
}

# Workspace tiling
dwindle {
    pseudotile = yes							# master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes						# split will not change regardles sof container
}

# Window decoration
decoration {
	rounding = 5				# border rounding

	shadow {
    enabled = false					# drop shadow
    range = 4								# drop shadow size in px
    render_power = 3				# shadow power falloff
    color = rgba(1a1a1aee)	# shadow collor
	}

	blur {
    enabled = true	# blur
    size = 3				# blur distance
		passes = 1			# passes to perform
	}

}

# Window animations
animations {
    enabled = yes

    bezier = myBezier, 0.22, 1.0, 0.36, 1

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, slide
    animation = border, 1, 20, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

###---Workspace-Config---###
workspace = 1, default:true, persistent:true
workspace = 2, default:true, persistent:true
workspace = 3, default:true, persistent:true

###---Game-Workspace-Config---###
# workspace = name:game, persistent:true
windowrule = workspace game, initialClass:^(gamescope)$
windowrule = workspace name:game, initialClass:(steam_app_default)
windowrule = tile, initialClass:^(Tabletop Simulator)(.*)$

# Window rules

# windowrule = center, floating:1
windowrule = float, class:^(pavucontrol)$
windowrule = float, class:^(blueman-manager)$
windowrule = float, class:^(nm-connection-editor)$

# layer rules
