#Main Hyprland config, see sourcefiles for implemented settings

source = ./core/autostart.conf #Autostart config
source = ./core/device-input.conf #Keybinds config
source = ./core/decoration.conf #Decoration config
